### ISSUE TITLE
Mock Bank Transfers do not work despite whitelisting server IP Address

### ISSUE THREAD

**Issue by jzagalo** [thecodecafe/react-native-flutterwave#74]
Hi Flutterwave,

I have been trying to mock a bank transfer to a Nigerian Bank Account, but I keep getting the error, "This transaction cannot be competed, please contact the administrator". Please also try to make your forum question and answers forum open to the public. There seems to be a famine of information on how to resolve Flutterwave integration problems and your forum which could do a world of difference seem not to be working at all. I registered with two different email addresses but none got any confirmation email.

Please consider making Youtube videos just like Stripe on integration of Flutterwave.  I will be looking forward to your response.

**Comment by corneliusyaovi** [comment]
Hello @jzagalo,

Bank transfers(payouts) are not supported in this library. Kindly contact our [support team](mailto:hi@flutterwavego.com) for help with your integration.

Thank you for your feedback.
